# LTT probes makefile

obj-$(CONFIG_LTT_PROBE_CORE)	+= ltt-probe-core.o
obj-$(CONFIG_LTT_PROBE_COMPACT)	+= ltt-probe-compact.o
obj-$(CONFIG_LTT_PROBE_FS)	+= ltt-probe-fs.o
obj-$(CONFIG_LTT_PROBE_ARCH)	+= \
			ltt-probe-kernel_arch_$(ARCH).o
obj-$(CONFIG_LTT_PROBE_KERNEL)	+= ltt-probe-kernel.o
obj-$(CONFIG_LTT_PROBE_LIST)	+= ltt-probe-list.o
obj-$(CONFIG_LTT_PROBE_MM)	+= ltt-probe-mm.o
obj-$(CONFIG_LTT_PROBE_NET)	+= ltt-probe-net.o
obj-$(CONFIG_LTT_PROBE_LOCKING)	+= ltt-probe-locking.o
obj-$(CONFIG_LTT_PROBE_STACK)	+= ltt-probe-stack_arch_$(ARCH).o
