#
# Makefile for the TC90416 board specific parts of the kernel
#
# This file is subject to the terms and conditions of the GNU General Public
# License.  See the file "COPYING" in the main directory of this archive
# for more details.
#
# (C) Copyright TOSHIBA CORPORATION 2005-2007
# All Rights Reserved.
#

obj-y	 += irq.o setup.o prom.o
obj-$(CONFIG_PM)	+= pm.o pm_core_tc90417.o
